setOfNum = set()
inputNum1 = int(input("input number1: "))
setOfNum.add(inputNum1)
inputNum2 = int(input("input number2: "))
setOfNum.add(inputNum2)
inputNum3 = int(input("input number3: "))
setOfNum.add(inputNum3)
inputNum4 = int(input("input number4: "))
setOfNum.add(inputNum4)
inputNum5 = int(input("input number5: "))
setOfNum.add(inputNum5)
inputNum6 = int(input("input number6: "))
setOfNum.add(inputNum6)
inputNum7 = int(input("input number7: "))
setOfNum.add(inputNum7)
inputNum8 = int(input("input number8: "))
setOfNum.add(inputNum8)

print(setOfNum)