a = "valid"
bbb = "valid"
# @abc = "invalid"  #remember we cannot use special character iin variable name.
# a$bc = "invalid"
# abcd$ = "invalid"
_temp = "valid" #we can use underscore in variable name.
tem_po ="valid"
# 2d = "invalid" #cant start with number, but we can end with number.
# 5f5f = "invalid"
Foo3="valid"